# Generated by Django 2.0.6 on 2018-07-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RestLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'RestLeft',
            },
        ),
        migrations.CreateModel(
            name='RestRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'RestRight',
            },
        ),
        migrations.AddField(
            model_name='restcompare',
            name='rest_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RestLeft'),
        ),
        migrations.AddField(
            model_name='restcompare',
            name='rest_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RestRight'),
        ),
    ]
