# Generated by Django 2.0.7 on 2018-07-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restcompare',
            name='rest_left',
        ),
        migrations.RemoveField(
            model_name='restcompare',
            name='rest_right',
        ),
        migrations.DeleteModel(
            name='RestCompare',
        ),
    ]
